version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_MESSAGE_MAX_BYTES=200000000
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=200000000
      - ALLOW_PLAINTEXT_LISTENERS=yes
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server kafka-1:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-instance-1:
    build: .
    container_name: app_instance_1
    depends_on:
      kafka-1:
        condition: service_healthy
    environment:
      - SERVER_PORT=8090
      - SPRING_APPLICATION_NAME=instance1
      - SPRING_KAFKA_CONSUMER_FIRST_TURN_CLAIM_GROUP_ID=first-turn-claim-group-id-1
      - SPRING_KAFKA_CONSUMER_GAME_MOVE_GROUP_ID=game-move-group-id-1
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka-1:9092
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka-1:9092
      - SPRING_KAFKA_PRODUCER_MAX_REQUEST_SIZE=200000000
      - SPRING_KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=200000000
    ports:
      - "8090:8090"

  app-instance-2:
    build: .
    container_name: app_instance_2
    depends_on:
      kafka-1:
        condition: service_healthy
    environment:
      - SERVER_PORT=8091
      - SPRING_APPLICATION_NAME=instance2
      - SPRING_KAFKA_CONSUMER_FIRST_TURN_CLAIM_GROUP_ID=first-turn-claim-group-id-2
      - SPRING_KAFKA_CONSUMER_GAME_MOVE_GROUP_ID=game-move-group-id-2
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka-1:9092
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka-1:9092
      - SPRING_KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=200000000
    ports:
      - "8091:8091"
