server:
  port: ${SERVER_PORT}
tic-tac-toe:
  move:
    delay: ${TIC_TAC_TOE_MOVE_DELAY}
  kafka:
    first-turn-claim:
      topic:
        name: first-turn-claim-topic
    game-move:
      topic:
        name: game-move-topic

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: jdbc:postgresql://postgres:5432/tic_tac_toe
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # todo - replace it with Liquibase approach
    show-sql: true
    properties:
      hibernate:
        physical_naming_strategy: com.scentbird.tictactoe.tictactoe.config.CustomPhysicalNamingStrategy

  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
      first-turn-claim:
        group-id: ${FIRST_TURN_SPRING_KAFKA_CONSUMER_GROUP_ID}
      game-move:
        group-id: ${GAME_MOVE_SPRING_KAFKA_CONSUMER_GROUP_ID}
    producer:
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

